# Basic

In [1]:
print("Day 1 Basic Python")

Day 1 Basic Python


# Data Types in Python

In [2]:
a = 10 
print("Type of a: ", type(a))  
b = 20.0 
print("\nType of b: ", type(b))  
c = 5 + 7j 
print("\nType of c: ", type(c)) 

Type of a:  <class 'int'>

Type of b:  <class 'float'>

Type of c:  <class 'complex'>


# Comparison Operators

In [3]:
a=20
b=30

In [4]:
a<b

True

In [5]:
a!=b

True

In [6]:
a==b

False

In [7]:
a<=b

True

In [8]:
a>=b

False

# Arthematic Operators

In [9]:
a=100
b=150

In [10]:
a+b

250

In [11]:
a-b

-50

In [12]:
a*b

15000

In [13]:
a/b

0.6666666666666666

In [14]:
a//b

0

In [15]:
a**b

1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [16]:
+a

100

In [17]:
-b

-150

#  Sequence Type

# String

In [18]:
str = "Hello my name is Ajay."
print(len(str))

22


# List

In [19]:
thislist = list((1, "apple", "banana", "cherry", 2))
print(thislist)

[1, 'apple', 'banana', 'cherry', 2]


In [20]:
print(type(thislist))

<class 'list'>


In [21]:
print(thislist[3:])

['cherry', 2]


In [22]:
print(thislist[0:2])

[1, 'apple']


In [23]:
print(thislist*3)

[1, 'apple', 'banana', 'cherry', 2, 1, 'apple', 'banana', 'cherry', 2, 1, 'apple', 'banana', 'cherry', 2]


# Tuple

In [24]:
thistuple = (1, "apple", "banana", "cherry", 2)
print(thistuple)

(1, 'apple', 'banana', 'cherry', 2)


In [25]:
print(thistuple[1:])

('apple', 'banana', 'cherry', 2)


In [26]:
print(thistuple[0:2])

(1, 'apple')


In [27]:
print(thistuple*3)

(1, 'apple', 'banana', 'cherry', 2, 1, 'apple', 'banana', 'cherry', 2, 1, 'apple', 'banana', 'cherry', 2)


# Dictionary

In [28]:
dict={1:"Python",2:"Is",3:"Powerful"}
print("\n Created Dictionary is:")
print(dict)


 Created Dictionary is:
{1: 'Python', 2: 'Is', 3: 'Powerful'}


In [29]:
del dict[2]
print("\n Updated Dictionary is:")
print(dict)


 Updated Dictionary is:
{1: 'Python', 3: 'Powerful'}


# Sets

In [30]:
thisset={'James','Python'}
print(thisset)

{'Python', 'James'}


# Types of Conditional Statements

# Simple if statement


In [31]:
a=33
b=200
if b>a:
    print("b is greater than a")

b is greater than a


# if – else statement

In [32]:
a=200
b=33
if b>a:
    print("b is greater than a")
else:
    print("b is not greater than a")

b is not greater than a


# elif- statement

In [33]:
a = 33
b=33
if b>a:
    print("b is greater than a")
elif a==b:
    print("a and b are equal")

a and b are equal


# While Loop

In [34]:
i=1
while i<6:
    print(i)
    i+=1

1
2
3
4
5


# For Loop

In [35]:
names=["Ajay","Jayanth","Devarsh","SathyaSuresh","Charan"]
for x in names:
    print(x)

Ajay
Jayanth
Devarsh
SathyaSuresh
Charan


# Built-in Functions

In [36]:
list1 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(list1[2:][:3])
print(list1[3:][:3])
list2= ["apple", "banana", "cherry"]
if "apple" in list2:
  print("Yes, 'apple' is in the fruits list")
list2.insert(2, 'watermelon')
print(list2) 
list3= ["apple", "banana", "cherry"]
list3.insert(3, 'orange')
print(list3)
list4= ["apple", "banana", "cherry"]
list4.insert(1, 'orange')
print(list4)
list5= ["apple", "banana", "cherry"]
more_list= ['mango', 'pineapple', 'papaya']
list5.extend(more_list)
print(list5)
list6= ["apple", "banana", "cherry"]
list6.remove('banana')
print(list6)
list7= ["apple", "banana", "cherry"]
list7.remove('apple')
print(list7)
list7.clear()
print(list7)

['cherry', 'orange', 'kiwi']
['orange', 'kiwi', 'melon']
Yes, 'apple' is in the fruits list
['apple', 'banana', 'watermelon', 'cherry']
['apple', 'banana', 'cherry', 'orange']
['apple', 'orange', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']
['apple', 'cherry']
['banana', 'cherry']
[]


# Prime Number

In [37]:
num=2
flag=False

if num>1:
    for i in range(2,num):
        if num%i ==0:
            flag=True
        break
if flag:
    print("num is not a prime number",num)
else:
    print("num is a prime number",num)

num is a prime number 2


# Factorial

In [38]:
num = 56
factorial = 1
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

The factorial of 56 is 710998587804863451854045647463724949736497978881168458687447040000000000000


# nPr

In [39]:
import math
def fact(n):
    if (n <= 1):
        return 1

    return n * fact(n - 1)

def nPr(n, r):

    return math.floor(fact(n) /
                fact(n - r))

n = 67
r = 2

print(n, "P", r, "=", nPr(n, r))

67 P 2 = 4422


# Sum of First and Last digit

In [40]:
print("Enter a Number: ")
num = int(input())

count = 0
while num!=0:
    if count==0:
        last = num%10
        count = count+1
    rem = num%10
    num = int(num/10)

sum = rem + last
print("\nSum of first and last digit =", sum)

Enter a Number: 
17643

Sum of first and last digit = 4


# Palindrome

In [41]:
n=int(input("Enter number:"))
temp=n
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
if(temp==rev):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")

Enter number:121
The number is a palindrome!


In [42]:
n=int(input("Enter number:"))
temp=n
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
if(temp==rev):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")

Enter number:69
The number isn't a palindrome!


# Armstrong

In [43]:
num = int(input("enter a number:"))
sum = 0
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10


if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

enter a number:153
153 is an Armstrong number


In [44]:
num = int(input("enter a number:"))
sum = 0
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10


if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

enter a number:69
69 is not an Armstrong number


# NUMPY Library

In [45]:
import numpy as np

In [46]:
li=np.array([[1,2,3],[4,5,6]])
print(li)

[[1 2 3]
 [4 5 6]]


In [47]:
print(li.shape)

(2, 3)


In [48]:
# Multi Dimentional Arrays

In [49]:
a=np.array([1,2,3,7])
b=np.array([4,5,6,4])
c=np.array([8,5,6,4])
abc=np.array([a,b,c])
print(abc)

[[1 2 3 7]
 [4 5 6 4]
 [8 5 6 4]]


In [50]:
print(abc.shape)

(3, 4)


In [51]:
print(abc.size)

12


In [52]:
#Array reshaping and indexing

In [53]:
n=abc.reshape(2,6)
print(n)

[[1 2 3 7 4 5]
 [6 4 8 5 6 4]]


In [54]:
print(n.shape)

(2, 6)


In [55]:
print(abc[0,0])

1


In [56]:
#Array of Zeros

In [57]:
zeroarray=np.zeros((3,3))
print(zeroarray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
#Slicing

In [59]:
print(abc[:,1:3:1])

[[2 3]
 [5 6]
 [5 6]]


In [60]:
#Boolean Functions

In [61]:
ajay=abc<3
print(ajay)

[[ True  True False False]
 [False False False False]
 [False False False False]]


In [62]:
#Where Method

In [63]:
sat=np.where(abc>5,abc,5)
print(sat)

[[5 5 5 7]
 [5 5 6 5]
 [8 5 6 5]]


In [64]:
print(a.sum())

13


In [65]:
print(a.cumsum())

[ 1  3  6 13]


In [66]:
print(a.prod())

42


In [67]:
print(a.cumprod())

[ 1  2  6 42]


In [68]:
#two array math operations

In [69]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 5  7  9 11]
[-3 -3 -3  3]
[ 4 10 18 28]
[0.25 0.4  0.5  1.75]
